apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsg-teller
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dsg-teller
  template:
    metadata:
      labels:
        app: dsg-teller
    spec:
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/dsg-teller:1.0.8
        name: dsg-teller
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URL
          value: "mongodb+srv://stage-dsguser:pz8fR7swzFNd3dka@stage-dsg-42wuh.mongodb.net/DSG?retryWrites=true&w=majority"