apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsg-teller
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dsg-teller
  template:
    metadata:
      labels:
        app: dsg-teller
    spec:
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/dsg-teller:1.0.8
        name: dsg-teller
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URL
          value: mongodb://stage-dsguser:pz8fR7swzFNd3dka@stage-dsg-shard-00-00-42wuh.mongodb.net:27017,stage-dsg-shard-00-01-42wuh.mongodb.net:27017,stage-dsg-shard-00-02-42wuh.mongodb.net:27017/DSG?ssl=true&replicaSet=stage-dsg-shard-0&authSource=admin&retryWrites=true&w=majority