apiVersion: apps/v1
kind: Deployment
metadata:
  name: dollarsmartglobal-com
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dollarsmartglobal-com
  template:
    metadata:
      labels:
        app: dollarsmartglobal-com
    spec:
      containers:
      - image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/dollarsmartglobal-com:1.0.17
        name: dollarsmartglobal-com
        ports:
        - containerPort: 80